### PR TITLE
Fix screensaver  for nanosp/nanox and add PIN lock in screensaver/app exit

### LINKED ISSUE #45: Nano(sp/x) screensave needs to be fixed.

### LINKED ISSUE #52: Lock the ledger when baking app exits
When the baking app quits , the ledger should go in pin locked mode. 
It is important as ledger remain unlocked when baking app is open for extended periods of time for baking. For additional security it is important that when we exit baking app, we should immediately lock the ledger.

### PR DESCRIPTION
**Pull request by ajinkyaraj-23**
Fixes #45  and  fixes #52

### CODE REVIEW

File: src/ui_empty.c [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+}
+
+void ux_layout_empty_screen_init(__attribute__((unused)) unsigned int x) {
+}
+
+void return_to_idle() {
+    ux_idle_screen(NULL, NULL);
+}
+
+UX_STEP_CB(empty_screen_step, empty, return_to_idle(), {" "});
```
Comment (spalmer25) [inline src/ui_empty.c:52]: The `" "` is not used. The `empty` layout you've created could have no line1.
In that case, the `ux_layout_strings_prepro` is unnecessary .

File: src/ui_empty.c [hunk 2]
```diff
@@ -0,0 +1,62 @@
...
+      116,
+      32,
+      0,
+      0,
+      0,
+      0xFFFFFF,
+      0x000000,
+      BAGL_FONT_OPEN_SANS_EXTRABOLD_11px | BAGL_FONT_ALIGNMENT_CENTER,
+      0},
+     .text = NULL}};
```
Comment (spalmer25) [inline src/ui_empty.c:29]: I'm not sure this element is needed as there is no text display, right ?

File: src/ui_empty.c [hunk 3]
```diff
@@ -0,0 +1,62 @@
...
+
+#include "ui.h"
+
+const bagl_element_t empty_screen_elements[] = {
+#if (BAGL_WIDTH == 128 && BAGL_HEIGHT == 64)
+    {{BAGL_RECTANGLE, 0x00, 0, 0, 128, 64, 0, 0, BAGL_FILL, 0x000000, 0xFFFFFF, 0, 0},
+     .text = NULL},
+#elif (BAGL_WIDTH == 128 && BAGL_HEIGHT == 32)
+    {{BAGL_RECTANGLE, 0x00, 0, 0, 128, 32, 0, 0, BAGL_FILL, 0x000000, 0xFFFFFF, 0, 0},
+     .text = NULL},
```
Comment (spalmer25) [inline src/ui_empty.c:12]: You can probably just write 
```
{{BAGL_RECTANGLE, BAGL_NONE, 0, 0, BAGL_WIDTH, BAGL_HEIGHT, 0, 0, BAGL_FILL, 0x000000, 0xFFFFFF, 0, 0},
     .text = NULL},
```

File: src/apdu_sign.c [hunk 4]
```diff
@@ -359,6 +359,7 @@ size_t handle_apdu_sign_with_hash(uint8_t instruction, volatile uint32_t *flags)
 int perform_signature(bool const on_hash, bool const send_hash) {
 #ifdef BAKING_APP
     write_high_water_mark(&G.parsed_baking_data);
+    ux_empty_screen();
```
Comment (spalmer25) [inline src/apdu_sign.c:362]: Each time an operation is being signed the `saverscreen` is redisplayed.
But in the specification (https://github.com/trilitech/ledger-app-tezos-baking/issues/21#issuecomment-1956295940), only baking operation should trigger the `saverscreen` and only if it is not activated.

**Review by spalmer25 — COMMENTED** [review]
The pin code should be required to exit the screen saver.

File: src/ui_empty.c (hunk 1 above)
Comment (ajinkyaraj-23) [reply src/ui_empty.c]: Removed.

File: src/apdu_sign.c (hunk 4 above)
Comment (ajinkyaraj-23) [reply src/apdu_sign.c]: Added a global bool to make sure the screensaver is triggered only when it is not active.

**Comment by ajinkyaraj-23** [comment]
> The pin code should be required to exit the screen saver.

Created a new issue as discussed #52

File: src/apdu_sign.c [hunk 5]
```diff
@@ -285,7 +285,9 @@ size_t handle_apdu_sign_with_hash(uint8_t instruction, volatile uint32_t *flags)
 
 int perform_signature(bool const on_hash, bool const send_hash) {
     write_high_water_mark(&G.parsed_baking_data);
-
+    if (global.is_blank_screen == false) {
+        ux_empty_screen();
+    }
```
Comment (spalmer25) [inline src/apdu_sign.c:290]: Maybe it could be better to check this condition in the `ux_empty_screen` itself

File: test/python/test_instructions.py [hunk 6]
```diff
@@ -336,6 +336,7 @@ def test_sign_preattestation(
         snap_path=snap_path / "app_context"
     )
 
+    tezos_navigator.backend.right_click()
```
Comment (spalmer25) [inline test/python/test_instructions.py:339]: `right_click` without waiting for something afterwards is not safe. At least wait until the screen has changed.

File: src/ui_empty.c [hunk 7]
```diff
@@ -37,6 +37,9 @@ void ux_layout_empty_screen_init(__attribute__((unused)) unsigned int x) {
 
 void return_to_idle() {
     global.is_blank_screen = false;
+    // before exiting the screensaver, force a device lock
+    bolos_ux_params_t params = {.ux_id = BOLOS_UX_VALIDATE_PIN};
+    os_ux_blocking(&params);
```
Comment (spalmer25) [inline src/ui_empty.c:42]: Duplicate code from `require_pin`

File: src/apdu_sign.c [hunk 8]
```diff
@@ -285,7 +285,9 @@ size_t handle_apdu_sign_with_hash(uint8_t instruction, volatile uint32_t *flags)
 
 int perform_signature(bool const on_hash, bool const send_hash) {
     write_high_water_mark(&G.parsed_baking_data);
-
+    if (global.is_blank_screen == false) {
+        ux_empty_screen();
```
Comment (spalmer25) [inline src/apdu_sign.c:289]: This code will be called for each signing not only `block` and `consensus operation` signing.
For example: `Delegation` and/or `Reveal`

File: src/globals.h [hunk 9]
```diff
@@ -101,6 +101,7 @@ typedef struct {
     void *stack_root;
     apdu_handler handlers[INS_MAX + 1];
     bip32_path_with_curve_t path_with_curve;
+    bool is_blank_screen;
```
Comment (spalmer25) [inline src/globals.h:104]: It makes more sense to me to have this field in the `dynamic_display` field.

File: src/ui_empty.c [hunk 10]
```diff
@@ -0,0 +1,54 @@
...
+                                                  BAGL_FILL,
+                                                  0x000000,
+                                                  0xFFFFFF,
+                                                  0,
+                                                  0},
+                                                 .text = NULL},
+                                                {}};
+
+typedef struct ux_layout_empty_params_s {
+    const char *line1;
```
Comment (spalmer25) [inline src/ui_empty.c:23]: This `line1` is unused and can be removed. According to the `empty_screen_step` argument

Comment (ajinkyaraj-23) [reply src/ui_empty.c:23]: Removed.

File: src/globals.h (hunk 9 above)
Comment (ajinkyaraj-23) [reply src/globals.h:104]: Done.

File: src/apdu_sign.c (hunk 8 above)
Comment (ajinkyaraj-23) [reply src/apdu_sign.c:296]: moved to guard_baking_authorized.

File: src/ui_empty.c (hunk 7 above)
Comment (ajinkyaraj-23) [reply src/ui_empty.c]: removed as no PIN after screensaver.

File: src/apdu_sign.c (hunk 5 above)
Comment (ajinkyaraj-23) [reply src/apdu_sign.c:297]: Done.

File: test/python/test_instructions.py (hunk 6 above)
Comment (ajinkyaraj-23) [reply test/python/test_instructions.py:339]: What would be right way to implement it as we dont expect any change in the screen when screensaver has turned on. To wake up from screensaver, this right click is implemented. 
Even in check_app_context, we navigate with `            self.navigator.navigate(
                [NavInsID.RIGHT_CLICK] * 2,
                screen_change_before_first_instruction=False
            )`

File: src/apdu_sign.c [hunk 11]
```diff
@@ -124,6 +124,7 @@ size_t baking_sign_complete(bool const send_hash, volatile uint32_t *flags) {
         case MAGIC_BYTE_BLOCK:
         case MAGIC_BYTE_BAKING_OP:
             guard_baking_authorized(&G.parsed_baking_data, &global.path_with_curve);
+            ux_empty_screen();
```
Comment (spalmer25) [inline src/apdu_sign.c:127]: `perform_signature` could THROW an error. Do we want the screen to blank in that case?

File: test/python/test_instructions.py (hunk 6 above)
Comment (spalmer25) [reply test/python/test_instructions.py:339]: The `screen_change_before_first_instruction=False` option is used to start navigating on the current screen (i.e. the navigator takes the first snapshot directly and does not expect the screen to change before starting to navigate).
And we expect the screen to change because before the `right_click` the screen was empty and after the `right_click` the screen became the first page of the home screen.

Comment (spalmer25) [reply test/python/test_instructions.py:339]: The `screen_change_before_first_instruction=False` option is used to start navigating on the current screen (i.e. the navigator takes the first snapshot directly and does not expect the screen to change before starting to navigate).
And we expect the screen to change because before the `right_click` the screen was empty and after the `right_click` the screen became the first page of the home screen.

File: src/apdu_sign.c (hunk 11 above)
Comment (ajinkyaraj-23) [reply src/apdu_sign.c:129]: Changed the baking_sign_complete return flow, to make sure ux_empty_screen() is called after successful perform_signature.

File: test/python/test_instructions.py (hunk 6 above)
Comment (ajinkyaraj-23) [reply test/python/test_instructions.py:339]: Understood. Added a screen check to make sure we have exited the screensaver and are on the Home screen.

File: test/python/test_instructions.py [hunk 12]
```diff
@@ -386,6 +391,12 @@ def test_sign_attestation(
...
+    tezos_navigator.assert_screen(
+        name="home_screen",
+        snap_path=snap_path / "app_context"
+    )
+
```
Comment (spalmer25) [inline test/python/test_instructions.py:399]: Since this code is duplicated, I think it could be worth to add a `black_screen` boolean argument (default false) to `check_app_context` and move the :
```python
    tezos_navigator.assert_screen(
        name="black_screen",
        snap_path=snap_path / "app_context"
    )

    tezos_navigator.backend.right_click()
    
    tezos_navigator.assert_screen(
        name="home_screen",
        snap_path=snap_path / "app_context"
    )
```
at the start of the home screen checks in `check_app_context`

Comment (ajinkyaraj-23) [reply test/python/test_instructions.py:399]: Done.

**Review by spalmer25 — APPROVED** [review]
LGTM
