### PR TITLE
Reveal: allows to sign a reveal

### LINKED ISSUE #11: Failed to sign a reveal
The signature of a reveal operation seems authorised but fails.

### PR DESCRIPTION
**Pull request by spalmer25**
This MR try to fix #11: 
- Split `reveal` and `delegation` cases at `baking_sign_complete`
- Do not check the `destination` for `reveal`
- Do not display for `reveal`
- Check the source for `reveal`
- Add tests that check that signing a `reveal` work
- Add tests that check the constraints of signing a `reveal`
- Add tests that check that at only batches that only operation batches with at most one delegation (not including `reveals`) are authorised to be signed.

### CODE REVIEW

File: src/apdu_sign.c [hunk 1]
```diff
@@ -160,16 +160,35 @@ size_t baking_sign_complete(bool const send_hash, volatile uint32_t *flags) {
...
+                    THROW(EXC_SECURITY);
+                    break;
+                case OPERATION_TAG_ATHENS_REVEAL:
+                case OPERATION_TAG_BABYLON_REVEAL:
+                case OPERATION_TAG_NONE:
+                    // Reveal cases
+                    if (bip32_path_with_curve_eq(&global.path_with_curve, &N_data.baking_key) &&
+                        // ops->signing is generated from G.bip32_path and G.curve
+                        COMPARE(&G.maybe_ops.v.operation.source, &G.maybe_ops.v.signing) == 0)
+                        return perform_signature(true, send_hash);
```
Comment (ajinkyaraj-23) [inline src/apdu_sign.c:187]: Should we use delayed_send here? It is being used for delegation right now.

Comment (spalmer25) [reply src/apdu_sign.c:187]: `delayed_send` and `delayed_reject` are used when something is displayed.
If I decide to send the response without displaying anything, we can simply `perform_signature` as is the case with "SAFEOP" : https://github.com/trilitech/ledger-app-tezos-baking/blob/main/src/apdu_sign.c#L157
